Repository farmersanonymous/killer-bunnies, pull requests merged in 2020-05, with the labels that each got.

#47 Character Controller
  src/environment/proxyGround.ts
  src/index.ts
  src/player/characterController.ts
  src/player/farmer.ts
  src/store/babylonStore.ts
Labels: enhancement

#52 Setup Continuous Deployment for pull requests and develop
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
Labels: enhancement

#53 Simple shooting mechanic LMB (mouse) RIght Trigger (gamepad)
  src/player/bullet.ts
  src/player/characterController.ts
  src/player/farmer.ts
Labels: enhancement

#54 Added basic collision detection
  src/environment/proxyCube.ts
  src/index.ts
  src/player/bullet.ts
  src/player/farmer.ts
  src/util/collisionGroup.ts
Labels: enhancement

#55 Added Garden proxy model
  src/environment/garden.ts
  src/environment/proxyCube.ts
  src/index.ts
  src/player/farmer.ts
  webpack.config.js
Labels: enhancement

#57 Added player proxy. Created spawner system.
  src/environment/garden.ts
  src/index.ts
  src/player/farmer.ts
  src/util/spawner.ts
Labels: enhancement

#59 Added stats for the Farmer.
  src/player/farmer.ts
Labels: enhancement

#63 Fixed bug where deployments were not caching immediately
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
Labels: bug

#61 Basic Game Loop. Unloading/Loading all resources.
  index.html
  src/camera/playerCameraController.ts
  src/environment/garden.ts
  src/environment/proxyCube.ts
  src/environment/proxyGround.ts
  src/game.ts
  src/index.ts
  src/player/bullet.ts
  src/player/characterController.ts
  src/player/farmer.ts
  src/store/babylonObserverStore.ts
  src/store/babylonStore.ts
  src/util/input.ts
  src/util/loader.ts
  src/util/spawner.ts
Labels: enhancement

#65 Added basic spawning system with Burrows
  src/environment/burrow.ts
  src/game.ts
  src/gameplay/roundHandler.ts
  src/player/bullet.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
Labels: enhancement

#75 Added AI for StabberBunnies. Cleaned up the update loop. Farmer input now based on NavMesh
  index.html
  src/enemies/stabberRabbit.ts
  src/environment/burrow.ts
  src/environment/garden.ts
  src/environment/proxyCube.ts
  src/game.ts
  src/gameplay/navigation.ts
  src/gameplay/roundHandler.ts
  src/index.ts
  src/player/bullet.ts
  src/player/farmer.ts
  src/store/babylonStore.ts
  src/util/spawner.ts
Labels: enhancement

#79 Added an animation system and set animations to play properly on the Farmer.
  src/animation/animator.ts
  src/assets/loader.ts
  src/assets/spawner.ts
  src/collision/collisionGroup.ts
  src/enemies/stabberRabbit.ts
  src/environment/burrow.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/gameplay/navigation.ts
  src/gameplay/roundHandler.ts
  src/index.ts
  src/input/input.ts
  src/player/bullet.ts
  src/player/characterController.ts
  src/player/farmer.ts
Labels: enhancement

#84 Added burrow asset and spawning at proper locations.
  src/environment/burrow.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/gameplay/roundHandler.ts
  src/index.ts
Labels: enhancement

#88 Smaller bullets
  src/enemies/stabberRabbit.ts
  src/index.ts
  src/player/bullet.ts
  src/player/farmer.ts
Labels: enhancement

#93 Updated the rabbits so that they will retreat properly.
  config.json
  src/enemies/stabberRabbit.ts
  src/gameplay/config.ts
  src/gameplay/navigation.ts
  src/gameplay/roundHandler.ts
Labels: enhancement

#94 Update well and meteorite
  config.json
  src/environment/garden.ts
Labels: enhancement

#104 Issue/24
  src/enemies/stabberRabbit.ts
  src/gameplay/game.ts
  src/player/characterController.ts
  src/player/farmer.ts
  src/ui/radar.ts
Labels: enhancement

#105 Carrots getting spawned.
  config.json
  src/environment/burrow.ts
  src/environment/carrot.ts
  src/environment/garden.ts
  src/gameplay/config.ts
  src/gameplay/roundHandler.ts
Labels: enhancement

#113 issue 74 - Added camera acceleration/decceleration for dampening effect.
  src/camera/playerCameraController.ts
  src/player/farmer.ts
Labels: enhancement

#114 Added pause mechanic and menu.
  config.json
  src/animation/animator.ts
  src/enemies/stabberRabbit.ts
  src/gameplay/game.ts
  src/gameplay/roundHandler.ts
  src/index.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
  src/ui/radar.ts
Labels: enhancement

#116 Fixed collision issue.
  config.json
  src/environment/garden.ts
Labels: enhancement

#118 Added gathering mechanic.
  config.json
  src/environment/carrot.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/gameplay/roundHandler.ts
  src/index.ts
  src/input/input.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
Labels: enhancement

#120 Added upgrade menu, with upgrading of Farmer stats.
  config.json
  src/assets/loader.ts
  src/environment/carrot.ts
  src/environment/garden.ts
  src/gameplay/config.ts
  src/gameplay/game.ts
  src/gameplay/roundHandler.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
  src/ui/imageManager.ts
Labels: enhancement

#125 Issue/100
  config.json
  src/enemies/stabberRabbit.ts
  src/environment/burrow.ts
  src/gameplay/config.ts
  src/gameplay/roundHandler.ts
  src/player/farmer.ts
Labels: enhancement

#124 Added Stabber Rabbit. Does not have carrot weapon yet.
  config.json
  src/animation/animator.ts
  src/assets/spawner.ts
  src/collision/collisionManager.ts
  src/enemies/stabberRabbit.ts
  src/environment/burrow.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/gameplay/navigation.ts
  src/gameplay/roundHandler.ts
  src/player/bullet.ts
  src/player/farmer.ts
  src/ui/radar.ts
Labels: enhancement

#128 Full Controller Support with icons
  ATTRIBUTION.md
  config.json
  src/enemies/stabberRabbit.ts
  src/environment/carrot.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/gameplay/roundHandler.ts
  src/input/input.ts
  src/player/characterController.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
Labels: enhancement

#129 Added a whole bunch of sfx.
  ATTRIBUTION.md
  config.json
  src/assets/soundManager.ts
  src/enemies/nabberRabbit.ts
  src/enemies/stabberRabbit.ts
  src/environment/burrow.ts
  src/environment/carrot.ts
  src/environment/garden.ts
  src/gameplay/game.ts
  src/index.ts
  src/player/bullet.ts
  src/player/farmer.ts
  src/ui/guiManager.ts
  src/util/mathUtil.ts
Labels: sound
